<div class="modal fade" id="terms-modal" tabindex="-1" role="dialog" aria-labelledby="terms-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Terms of use</h4>
            </div>
            <div class="modal-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id nibh mi. Cras vehicula nisi a purus blandit porttitor. Nam sagittis imperdiet purus vel auctor. Donec lacus turpis, laoreet eu mi bibendum, blandit facilisis est. Etiam ut tempor justo. Aenean odio mauris, rhoncus vulputate ullamcorper sit amet, volutpat ut magna. Etiam nisl lorem, condimentum at leo pretium, volutpat varius nisl. Etiam elementum rutrum tellus at scelerisque. Integer pulvinar posuere molestie. Nulla facilisi. Praesent malesuada ante non odio posuere lobortis. Suspendisse potenti. Mauris in justo eleifend metus eleifend viverra. Nullam ac odio tristique nisi scelerisque finibus. Maecenas convallis faucibus imperdiet. Mauris vitae risus porttitor, egestas enim in, mattis eros.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id nibh mi. Cras vehicula nisi a purus blandit porttitor. Nam sagittis imperdiet purus vel auctor. Donec lacus turpis, laoreet eu mi bibendum, blandit facilisis est. Etiam ut tempor justo. Aenean odio mauris, rhoncus vulputate ullamcorper sit amet, volutpat ut magna. Etiam nisl lorem, condimentum at leo pretium, volutpat varius nisl. Etiam elementum rutrum tellus at scelerisque. Integer pulvinar posuere molestie. Nulla facilisi. Praesent malesuada ante non odio posuere lobortis. Suspendisse potenti. Mauris in justo eleifend metus eleifend viverra. Nullam ac odio tristique nisi scelerisque finibus. Maecenas convallis faucibus imperdiet. Mauris vitae risus porttitor, egestas enim in, mattis eros.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id nibh mi. Cras vehicula nisi a purus blandit porttitor. Nam sagittis imperdiet purus vel auctor. Donec lacus turpis, laoreet eu mi bibendum, blandit facilisis est. Etiam ut tempor justo. Aenean odio mauris, rhoncus vulputate ullamcorper sit amet, volutpat ut magna. Etiam nisl lorem, condimentum at leo pretium, volutpat varius nisl. Etiam elementum rutrum tellus at scelerisque. Integer pulvinar posuere molestie. Nulla facilisi. Praesent malesuada ante non odio posuere lobortis. Suspendisse potenti. Mauris in justo eleifend metus eleifend viverra. Nullam ac odio tristique nisi scelerisque finibus. Maecenas convallis faucibus imperdiet. Mauris vitae risus porttitor, egestas enim in, mattis eros.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id nibh mi. Cras vehicula nisi a purus blandit porttitor. Nam sagittis imperdiet purus vel auctor. Donec lacus turpis, laoreet eu mi bibendum, blandit facilisis est. Etiam ut tempor justo. Aenean odio mauris, rhoncus vulputate ullamcorper sit amet, volutpat ut magna. Etiam nisl lorem, condimentum at leo pretium, volutpat varius nisl. Etiam elementum rutrum tellus at scelerisque. Integer pulvinar posuere molestie. Nulla facilisi. Praesent malesuada ante non odio posuere lobortis. Suspendisse potenti. Mauris in justo eleifend metus eleifend viverra. Nullam ac odio tristique nisi scelerisque finibus. Maecenas convallis faucibus imperdiet. Mauris vitae risus porttitor, egestas enim in, mattis eros.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id nibh mi. Cras vehicula nisi a purus blandit porttitor. Nam sagittis imperdiet purus vel auctor. Donec lacus turpis, laoreet eu mi bibendum, blandit facilisis est. Etiam ut tempor justo. Aenean odio mauris, rhoncus vulputate ullamcorper sit amet, volutpat ut magna. Etiam nisl lorem, condimentum at leo pretium, volutpat varius nisl. Etiam elementum rutrum tellus at scelerisque. Integer pulvinar posuere molestie. Nulla facilisi. Praesent malesuada ante non odio posuere lobortis. Suspendisse potenti. Mauris in justo eleifend metus eleifend viverra. Nullam ac odio tristique nisi scelerisque finibus. Maecenas convallis faucibus imperdiet. Mauris vitae risus porttitor, egestas enim in, mattis eros.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id nibh mi. Cras vehicula nisi a purus blandit porttitor. Nam sagittis imperdiet purus vel auctor. Donec lacus turpis, laoreet eu mi bibendum, blandit facilisis est. Etiam ut tempor justo. Aenean odio mauris, rhoncus vulputate ullamcorper sit amet, volutpat ut magna. Etiam nisl lorem, condimentum at leo pretium, volutpat varius nisl. Etiam elementum rutrum tellus at scelerisque. Integer pulvinar posuere molestie. Nulla facilisi. Praesent malesuada ante non odio posuere lobortis. Suspendisse potenti. Mauris in justo eleifend metus eleifend viverra. Nullam ac odio tristique nisi scelerisque finibus. Maecenas convallis faucibus imperdiet. Mauris vitae risus porttitor, egestas enim in, mattis eros.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id nibh mi. Cras vehicula nisi a purus blandit porttitor. Nam sagittis imperdiet purus vel auctor. Donec lacus turpis, laoreet eu mi bibendum, blandit facilisis est. Etiam ut tempor justo. Aenean odio mauris, rhoncus vulputate ullamcorper sit amet, volutpat ut magna. Etiam nisl lorem, condimentum at leo pretium, volutpat varius nisl. Etiam elementum rutrum tellus at scelerisque. Integer pulvinar posuere molestie. Nulla facilisi. Praesent malesuada ante non odio posuere lobortis. Suspendisse potenti. Mauris in justo eleifend metus eleifend viverra. Nullam ac odio tristique nisi scelerisque finibus. Maecenas convallis faucibus imperdiet. Mauris vitae risus porttitor, egestas enim in, mattis eros.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->